image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
tasks:
  - init: flutter run --web-port 8080
vscode:
  extensions:
    - Dart-Code.flutter@3.6.0:bAElIiRvpBSK2AT2+PDj0w==
    - Dart-Code.dart-code@3.6.0:OIKJQXmfWHoIMVCiWrcLsQ==
